[package]
name = "lp-1189"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.9"
solana-program-test = "=1.18.9"
solana-sdk = "=1.18.9"

sanctum-solana-test-utils = { git = "https://github.com/igneous-labs/sanctum-solana-utils", branch = "master" }
tokio = "^1"
